"""
SQLAlchemy ORM models for TVA (Target Validation Assistant) database.

Database Schema:
1. users - User accounts and authentication
2. sessions - User sessions and login history
3. documents - PDF documents uploaded by users
4. document_chunks - Text chunks from documents for vector search
5. chat_messages - Chat conversation history
6. analysis_reports - Generated analysis reports
7. document_annotations - User annotations on documents
8. agent_logs - Execution logs for agents
9. api_usage - Track API usage for monitoring

Relationships:
- users (1) -> (many) sessions
- users (1) -> (many) documents
- users (1) -> (many) chat_messages
- documents (1) -> (many) document_chunks
- documents (1) -> (many) document_annotations
- documents (1) -> (many) analysis_reports
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum as SQLEnum,
    Float,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import declarative_base, relationship

from app.config.settings import settings

Base = declarative_base()


def get_korea_time():
    """Get current time in Korea timezone as naive datetime.
    
    PostgreSQL TIMESTAMP WITHOUT TIME ZONE requires naive datetime.
    We convert to naive datetime after getting Korea time.
    """
    korea_time = datetime.now(settings.timezone)
    # Convert to naive datetime (remove timezone info)
    return korea_time.replace(tzinfo=None)


class User(Base):
    """User account model."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, nullable=False, index=True)
    username = Column(String(100), unique=True, nullable=False, index=True)
    hashed_password = Column(String(255), nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    is_admin = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=get_korea_time, nullable=False)
    updated_at = Column(DateTime, default=get_korea_time, onupdate=get_korea_time, nullable=False)

    # Relationships
    sessions = relationship("Session", back_populates="user", cascade="all, delete-orphan")
    documents = relationship("Document", back_populates="user", cascade="all, delete-orphan")
    chat_messages = relationship("ChatMessage", back_populates="user", cascade="all, delete-orphan")

    __table_args__ = (Index("idx_user_email", "email"), Index("idx_user_username", "username"))


class Session(Base):
    """Chat/Work session model - represents a workspace for chat and document analysis."""

    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    analysis_goal = Column(Text, nullable=True)  # ✅ User's analysis target/goal
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=get_korea_time, nullable=False)
    updated_at = Column(DateTime, default=get_korea_time, onupdate=get_korea_time, nullable=False)

    # Relationships
    user = relationship("User", back_populates="sessions")

    __table_args__ = (
        Index("idx_session_user_id", "user_id"),
        Index("idx_session_created_at", "created_at"),
    )


class Document(Base):
    """PDF document model."""

    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    session_id = Column(Integer, ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    file_name = Column(String(255), nullable=False)  # Original filename
    file_path = Column(String(500), nullable=False)  # S3 or local path
    file_size = Column(Integer, nullable=False)  # bytes
    page_count = Column(Integer, nullable=True)  # ✅ From PDF
    mime_type = Column(String(50), default="application/pdf", nullable=False)
    is_indexed = Column(Boolean, default=False, nullable=False)  # Whether text extracted
    indexed_at = Column(DateTime, nullable=True)
    section_split_confidence = Column(String(50), default="unknown", nullable=False)  # "llm" or "fallback"
    
    # ✅ PDF Metadata (새로 추가)
    keywords = Column(JSON, nullable=True)  # ["CRISPR", "gene-editing"]
    sections = Column(JSON, nullable=True)  # ["1. Introduction", "2. Methods", ...]
    extracted_abstract = Column(Text, nullable=True)  # Abstract extracted from PDF
    summary = Column(Text, nullable=True)  # ✅ Core summary generated by SummaryAgent
    relevance_score = Column(Float, nullable=True)  # 0-1 score from LLM filtering
    source = Column(String(50), nullable=True)  # "arxiv", "pubmed", "manual_upload"
    external_id = Column(String(255), nullable=True)  # arxiv/pubmed ID
    
    created_at = Column(DateTime, default=get_korea_time, nullable=False)
    updated_at = Column(DateTime, default=get_korea_time, onupdate=get_korea_time, nullable=False)

    # Relationships
    user = relationship("User", back_populates="documents")
    session = relationship("Session", foreign_keys=[session_id])
    chunks = relationship("DocumentChunk", back_populates="document", cascade="all, delete-orphan")
    annotations = relationship("DocumentAnnotation", back_populates="document", cascade="all, delete-orphan")
    reports = relationship("AnalysisReport", back_populates="document", cascade="all, delete-orphan")

    __table_args__ = (
        Index("idx_document_user_id", "user_id"),
        Index("idx_document_session_id", "session_id"),
        Index("idx_document_indexed", "is_indexed"),
    )


class DocumentChunk(Base):
    """Text chunks from documents for vector search and analysis."""

    __tablename__ = "document_chunks"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    chunk_index = Column(Integer, nullable=False)  # Order within document
    page_number = Column(Integer, nullable=False)
    text_content = Column(Text, nullable=False)
    char_count = Column(Integer, nullable=False)
    chroma_id = Column(String(36), unique=True, nullable=True, index=True)  # UUID from ChromaDB
    embedding_model = Column(String(100), nullable=True)  # Which model created embedding
    created_at = Column(DateTime, default=get_korea_time, nullable=False)

    # Relationships
    document = relationship("Document", back_populates="chunks")

    __table_args__ = (
        Index("idx_chunk_document_id", "document_id"),
        Index("idx_chunk_chroma_id", "chroma_id"),
        Index("idx_chunk_page_number", "page_number"),
    )


class ChatMessage(Base):
    """Chat message history."""

    __tablename__ = "chat_messages"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    role = Column(String(20), nullable=False)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    model_used = Column(String(100), nullable=True)  # Which LLM model
    tokens_used = Column(Integer, nullable=True)  # For usage tracking
    created_at = Column(DateTime(timezone=True), default=get_korea_time, nullable=False)

    # Relationships
    user = relationship("User", back_populates="chat_messages")
    document = relationship("Document")

    __table_args__ = (
        Index("idx_message_session_id", "session_id"),
        Index("idx_message_user_id", "user_id"),
        Index("idx_message_document_id", "document_id"),
        Index("idx_message_created_at", "created_at"),
    )


class AnalysisReport(Base):
    """Generated analysis reports for documents."""

    __tablename__ = "analysis_reports"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    agent_type = Column(String(50), nullable=False)  # search_indexer, pdf_analyzer, rag_agent, report_writer
    report_type = Column(String(50), nullable=False)  # "summary", "analysis", "extraction", etc.
    title = Column(String(255), nullable=False)
    content = Column(Text, nullable=False)
    meta_data = Column(Text, nullable=True)  # JSON string with analysis details
    is_public = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=get_korea_time, nullable=False)
    updated_at = Column(DateTime, default=get_korea_time, onupdate=get_korea_time, nullable=False)

    # Relationships
    document = relationship("Document", back_populates="reports")

    __table_args__ = (
        Index("idx_report_document_id", "document_id"),
        Index("idx_report_agent_type", "agent_type"),
    )


class DocumentAnnotation(Base):
    """User annotations on specific parts of documents."""

    __tablename__ = "document_annotations"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    page_number = Column(Integer, nullable=False)
    highlight_text = Column(Text, nullable=True)
    note = Column(Text, nullable=True)
    annotation_type = Column(String(50), nullable=False)  # "highlight", "comment", "bookmark", etc.
    created_at = Column(DateTime, default=get_korea_time, nullable=False)
    updated_at = Column(DateTime, default=get_korea_time, onupdate=get_korea_time, nullable=False)

    # Relationships
    document = relationship("Document", back_populates="annotations")

    __table_args__ = (
        Index("idx_annotation_document_id", "document_id"),
        Index("idx_annotation_user_id", "user_id"),
    )


class AgentLog(Base):
    """Execution logs for agents."""

    __tablename__ = "agent_logs"

    id = Column(Integer, primary_key=True, index=True)
    agent_name = Column(String(100), nullable=False)  # search_indexer, pdf_analyzer, rag_agent, report_writer
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    status = Column(String(20), nullable=False)  # "pending", "running", "completed", "failed"
    input_data = Column(Text, nullable=True)  # JSON input
    output_data = Column(Text, nullable=True)  # JSON output
    error_message = Column(Text, nullable=True)
    execution_time_ms = Column(Integer, nullable=True)  # milliseconds
    tokens_used = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=get_korea_time, nullable=False)
    updated_at = Column(DateTime, default=get_korea_time, onupdate=get_korea_time, nullable=False)

    __table_args__ = (
        Index("idx_agent_log_agent_name", "agent_name"),
        Index("idx_agent_log_document_id", "document_id"),
        Index("idx_agent_log_status", "status"),
        Index("idx_agent_log_created_at", "created_at"),
    )


class SearchCache(Base):
    """Cache for search results with TTL."""

    __tablename__ = "search_cache"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    query_hash = Column(String(64), nullable=False)  # SHA-256 hash of query
    source = Column(String(20), nullable=False)  # 'arxiv', 'pubmed', 'both'
    papers_json = Column(Text, nullable=False)  # JSON array of papers
    result_count = Column(Integer, nullable=False)
    ttl_seconds = Column(Integer, default=604800)  # 7 days
    created_at = Column(DateTime, default=get_korea_time, nullable=False)
    expires_at = Column(DateTime, nullable=False)  # When cache expires
    accessed_at = Column(DateTime, default=get_korea_time, nullable=False)
    access_count = Column(Integer, default=1)

    __table_args__ = (
        Index("idx_search_cache_user_id", "user_id"),
        Index("idx_search_cache_query_hash", "query_hash"),
        Index("idx_search_cache_expires_at", "expires_at"),
        UniqueConstraint("user_id", "query_hash", "source", name="uq_search_cache_user_query_source"),
    )


class SearchHistory(Base):
    """Track user search history."""

    __tablename__ = "search_history"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    session_id = Column(Integer, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=True)
    query = Column(String(1000), nullable=False)
    source = Column(String(20), nullable=False)  # 'arxiv', 'pubmed', 'both'
    papers_found = Column(Integer, nullable=False)
    papers_downloaded = Column(Integer, default=0)
    papers_filtered = Column(Integer, nullable=False)  # After relevance filtering
    min_relevance_score = Column(Float, nullable=True)
    max_relevance_score = Column(Float, nullable=True)
    avg_relevance_score = Column(Float, nullable=True)
    search_time_seconds = Column(Float, nullable=False)
    from_cache = Column(Boolean, default=False)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=get_korea_time, nullable=False)

    __table_args__ = (
        Index("idx_search_history_user_id", "user_id"),
        Index("idx_search_history_session_id", "session_id"),
        Index("idx_search_history_created_at", "created_at"),
    )


class APIUsage(Base):
    """Track API usage for monitoring and billing."""

    __tablename__ = "api_usage"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    endpoint = Column(String(255), nullable=False)
    method = Column(String(10), nullable=False)  # GET, POST, PUT, DELETE
    status_code = Column(Integer, nullable=False)
    response_time_ms = Column(Integer, nullable=True)
    request_size_bytes = Column(Integer, nullable=True)
    response_size_bytes = Column(Integer, nullable=True)
    ip_address = Column(String(45), nullable=True)
    created_at = Column(DateTime, default=get_korea_time, nullable=False)

    __table_args__ = (
        Index("idx_usage_user_id", "user_id"),
        Index("idx_usage_endpoint", "endpoint"),
        Index("idx_usage_created_at", "created_at"),
    )
