"""
Pydantic schemas for document-related API requests and responses.

These schemas provide:
- Document upload and management request/response models
- Type-safe document data validation
- Automatic OpenAPI documentation
"""

from datetime import datetime
from typing import Optional
from zoneinfo import ZoneInfo

from pydantic import BaseModel, Field


KST = ZoneInfo("Asia/Seoul")


# ============================================================================
# Request Schemas (Input)
# ============================================================================


class DocumentUploadRequest(BaseModel):
    """Request schema for document upload."""

    title: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Document title (1-255 characters)",
    )
    description: Optional[str] = Field(
        None,
        max_length=1000,
        description="Optional document description",
    )
    session_id: Optional[str] = Field(
        None,
        description="Associated session ID (optional)",
    )

    class Config:
        json_schema_extra = {
            "example": {
                "title": "A Novel Approach to Target Validation",
                "description": "Research paper on target validation in drug discovery",
                "session_id": "sess_abc123",
            }
        }


# ============================================================================
# Response Schemas (Output)
# ============================================================================


class DocumentResponse(BaseModel):
    """Response schema for a single document."""

    id: str = Field(..., description="Unique document ID (UUID)")
    user_id: str = Field(..., description="User ID who uploaded this document")
    session_id: Optional[str] = Field(
        None,
        description="Associated session ID",
    )
    title: str = Field(..., description="Document title")
    description: Optional[str] = Field(None, description="Document description")
    file_name: str = Field(..., description="Original file name")
    file_size: int = Field(..., description="File size in bytes")
    file_path: str = Field(..., description="Storage path")
    mime_type: str = Field(..., description="MIME type (e.g., application/pdf)")
    page_count: int = Field(default=0, description="Number of pages")
    chunk_count: int = Field(default=0, description="Number of text chunks")
    summary: Optional[str] = Field(None, description="Core summary generated by SummaryAgent")
    is_processed: bool = Field(
        default=False,
        description="Whether document has been analyzed and chunked",
    )
    created_at: datetime = Field(..., description="Upload timestamp (KST)")
    updated_at: datetime = Field(..., description="Last update timestamp (KST)")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "user_id": "user_123",
                "session_id": "sess_abc123",
                "title": "A Novel Approach to Target Validation",
                "description": "Research paper on target validation",
                "file_name": "paper.pdf",
                "file_size": 2048000,
                "file_path": "/uploads/user_123/paper.pdf",
                "mime_type": "application/pdf",
                "page_count": 15,
                "chunk_count": 45,
                "summary": "This paper presents a novel framework for target validation...",
                "is_processed": True,
                "created_at": "2026-01-17T10:30:00+09:00",
                "updated_at": "2026-01-17T11:45:00+09:00",
            }
        }


class DocumentListResponse(BaseModel):
    """Response schema for document list with pagination."""

    documents: list[DocumentResponse] = Field(
        default=[],
        description="List of documents",
    )
    total_count: int = Field(default=0, description="Total number of documents")
    limit: int = Field(..., description="Pagination limit")
    offset: int = Field(..., description="Pagination offset")

    class Config:
        json_schema_extra = {
            "example": {
                "documents": [
                    {
                        "id": "550e8400-e29b-41d4-a716-446655440000",
                        "user_id": "user_123",
                        "title": "Paper 1",
                        "file_name": "paper1.pdf",
                        "file_size": 2048000,
                        "is_processed": True,
                        "created_at": "2026-01-17T10:30:00+09:00",
                    }
                ],
                "total_count": 1,
                "limit": 50,
                "offset": 0,
            }
        }


class DocumentDeleteResponse(BaseModel):
    """Response schema for document deletion."""

    document_id: str = Field(..., description="Deleted document ID")
    success: bool = Field(..., description="Deletion success")
    message: str = Field(..., description="Deletion message")
    timestamp: datetime = Field(..., description="Deletion timestamp (KST)")

    class Config:
        json_schema_extra = {
            "example": {
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "success": True,
                "message": "Document deleted successfully",
                "timestamp": "2026-01-17T16:00:00+09:00",
            }
        }


class MessageResponse(BaseModel):
    """General response schema for simple messages."""

    message: str = Field(..., description="Response message")
    success: bool = Field(default=True, description="Operation success")
    timestamp: Optional[datetime] = Field(None, description="Timestamp (KST)")

    class Config:
        json_schema_extra = {
            "example": {
                "message": "Operation completed successfully",
                "success": True,
                "timestamp": "2026-01-17T16:00:00+09:00",
            }
        }
